apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # 프론트 (rewrite해서 assets 경로 유지)
          - path: /()(.*)
            pathType: mplementationSpecific
            backend:
              service:
                name: ddis-frontend-service
                port:
                  number: 80

          # 백엔드 (rewrite /ddis → /)
          - path: /ddis(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: ddis-service
                port:
                  number: 8080
